# Generated by Django 5.0.3 on 2024-04-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_appointment_contacts_alter_doctors_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=70)),
                ('profession', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='testimonial/')),
                ('review', models.TextField()),
            ],
        ),
    ]
